# Generated by Django 5.2.8 on 2025-11-30 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=100)),
                ('anio_fundacion', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('fecha_publicacion', models.DateField()),
                ('numero_paginas', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('autores', models.ManyToManyField(related_name='libros', to='catalogo.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='catalogo.editorial')),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='PerfilAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio_web', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('premios', models.TextField(blank=True)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='catalogo.autor')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Autores',
            },
        ),
    ]
